services:
  sftp:
    image: docker.io/atmoz/sftp:alpine-3.7
    env_file:
      - ./.env
    ports:
      - '2222:22'
    volumes:
      - ./sftp/upload:/home/${SFTP_USER}/upload
      - ./sftp/etc/ssh/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key:ro
      - ./sftp/etc/ssh/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key:ro